block-blacklist:
  - "KELP"
  - "KELP_PLANT"
  - "GRASS"
  - "SEAGRASS"
  - "TALL_SEAGRASS"
  - "DANDELION"
  - "POPPY"
  - "BLUE_ORCHID"
  - "ALLIUM"
  - "AZURE_BLUET"
  - "RED_TULIP"
  - "ORANGE_TULIP"
  - "WHITE_TULIP"
  - "PINK_TULIP"
  - "OXEYE_DAISY"
  - "CORNFLOWER"
  - "LILY_OF_THE_VALLEY"
  - "TORCHFLOWER"
  - "PINK_PETALS"
  - "SPORE_BLOSSOM"
  - "ROSE_BUSH"
  - "GRASS"
  - "SAND"

update-interval: 20
world-blacklist:
  - world_nether
  - world_the_end
rewardProbability: 0.04
use-tool-money: true
tools:
  NETHERITE_PICKAXE: 250
  NETHERITE_SHOVEL: 250
  DIAMOND_PICKAXE: 200
  DIAMOND_SHOVEL: 200
  GOLDEN_PICKAXE: 175
  GOLDEN_SHOVEL: 175
  IRON_PICKAXE: 150
  IRON_SHOVEL: 150
  STONE_PICKAXE: 100
  STONE_SHOVEL: 100
  WOODEN_PICKAXE: 50
  WOODEN_SHOVEL: 50
