name: Digger
version: '${project.version}'
main: org.hotal.digger.Digger
api-version: '1.20'
load: STARTUP
author: ほたまちスバル
description: copyright 2023 NANDEYANEN エンジニア部 & ほたまちスバル
depend:
  - Vault
commands:
  reload:
    description: 設定を再読み込みします。
    usage: /reload
  set:
    description: プレイヤー別に強制的に掘ったブロックを設定します。
    usage: /set
  permissions:
  digger.reload:
    description: 設定を再読み込みします。
    default: op
  digger.set:
    description: プレイヤー別に強制的に掘ったブロックを設定します。
    default: op
