name: Digger
version: '${project.version}'
main: org.hotal.digger.Digger
api-version: '1.20'
load: STARTUP
depend:
  - Vault
commands:
  updatescoreboard:
    description: スコアボードをアップデートします（OP用）。
    usage: /updatescoreboard
  setprobability:
    description: 確率を変更します（OP用）。
    usage: /setprobability
  reload:
    description: 設定を再読み込みします。
    usage: /reload
  set:
      description: プレイヤー別に強制的に掘ったブロックを設定します。
      usage: /set
  sb:
    description: スコアボードを表示、非表示にします。
    usage: /sb <on/off>
  sutm:
    description: config.ymlのuse-tool-moneyの有効/無効を強制的に切り替えます。
    usage: /sutm <true/false>
permissions:
  digger.debug:
    description: スコアボードをアップデートします（OP限定）。
    default: op
  digger.setprobability:
    description: 確率を変更します。（OP限定）。
    default: op
  digger.reload:
    description: 設定を再読み込みします。
    default: op
  digger.set:
    description: プレイヤー別に強制的に掘ったブロックを設定します。
    default: op
  digger.sutm:
    description: config.ymlのuse-tool-moneyの有効/無効を強制的に切り替えます。
    default: op
