name: Digger
version: '${project.version}'
main: org.hotal.digger.Digger
api-version: '1.20'
load: STARTUP
depend:
  - Vault
commands:
  digger:
    usage: /digger [時間(分)]
  updatescoreboard:
    description: スコアボードをすぐにアップデートします（デバッグ用）。
    usage: /updatescoreboard
permissions:
  digger.minute:
    description: 更新時間を設定します。
    default: op
  digger.debug:
    description: スコアボードをアップデートします（デバッグ用）。
    default: op
