name: Digger
version: '${project.version}'
main: org.hotal.digger.Digger
api-version: '1.20'
load: STARTUP
depend:
  - Vault
commands:
  reload:
    description: 設定を再読み込みします。
    usage: /reload
  set:
      description: プレイヤー別に強制的に掘ったブロックを設定します。
      usage: /set
  sb:
    description: スコアボードを表示、非表示にします。
    usage: /sb <on/off>
permissions:
  digger.reload:
    description: 設定を再読み込みします。
    default: op
  digger.set:
    description: プレイヤー別に強制的に掘ったブロックを設定します。
    default: op
