block-blacklist:
  -"crimson_slab"
  -"warped_slab"
  -"stone_slab"
  -"smooth_stone_slab"
  -"sandstone_slab"
  -"cut_sandstone_slab"
  -"petrified_oak_slab"
  -"cobblestone_slab"
  -"brick_slab"
  -"stone_brick_slab"
  -"nether_brick_slab"
  -"quartz_slab"
  -"red_sandstone_slab"
  -"cut_red_sandstone_slab"
  -"purpur_slab"
  -"prismarine_slab"
  -"prismarine_brick_slab"
  -"dark_prismarine_slab"
  -"smooth_quartz"
  -"smooth_red_sandstone"
  -"smooth_sandstone"
  -"smooth_stone"
  -"bricks"
  -"bookshelf"
  -"purpur_block"
  -"purpur_pillar"
  -"purpur_stairs"
  -"oak_stairs"